[package]
name = "takehome"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.11"
lazy_static = "1.4.0"
# serialization
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_with = { version = "3.3", features = ["base64"] }
bincode = { version = "1.3.3" }
# misc
log = "0.4"
env_logger = "0.10"
getset = "0.1.2"
ark-std = { version = "0.3.0", features = ["print-trace"], optional = true }
anyhow = "1.0"
downcast-rs = "1.2.0"
hex = "0.4.3"
byteorder = { version = "1.4.3" }
rand = "0.8"
rand_core = { version = "0.6", default-features = false, features = ["getrandom"] }
rayon = "1.8.1"

[lib]
path = "src/lib.rs"